### ISSUE TITLE
Package "name" field doesn't match expected name "appwrite_account_kit"

### ISSUE THREAD

**Issue by markosole** [lohanidamodar/flutter_appwrite_starter#8]
Hi, 

Thnaks for great example app. I am having difficulty running it.

I am getting error below 

```Shell
Error on line 1, column 7: "name" field doesn't match expected name "appwrite_account_kit".
  ╷
1 │ name: appwrite_auth_kit
  │       ^^^^^^^^^^^^^^^^^
  ╵
```

Here is my pubspec file. 

```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  appwrite_account_kit:
    git: https://github.com/lohanidamodar/appwrite_auth_kit.git

```

The package name have been changed and I've tried updatind all dependencies but no joy.
